[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "n8n"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthz"
healthcheckTimeout = 300

# n8n Environment Variables
[[deploy.environmentVariables]]
name = "N8N_PROTOCOL"
value = "https"

[[deploy.environmentVariables]]
name = "N8N_HOST"
value = "${{RAILWAY_PUBLIC_DOMAIN}}"

[[deploy.environmentVariables]]
name = "WEBHOOK_URL"
value = "https://${{RAILWAY_PUBLIC_DOMAIN}}/"

[[deploy.environmentVariables]]
name = "N8N_EDITOR_BASE_URL"
value = "https://${{RAILWAY_PUBLIC_DOMAIN}}/"

[[deploy.environmentVariables]]
name = "N8N_BASIC_AUTH_ACTIVE"
value = "true"

[[deploy.environmentVariables]]
name = "N8N_BASIC_AUTH_USER"
value = "admin"

# Set a secure password - CHANGE THIS AFTER DEPLOYMENT
[[deploy.environmentVariables]]
name = "N8N_BASIC_AUTH_PASSWORD"
value = "changeme123"

[[deploy.environmentVariables]]
name = "GENERIC_TIMEZONE"
value = "Europe/London"

[[deploy.environmentVariables]]
name = "N8N_METRICS"
value = "true"

# Disable telemetry for privacy
[[deploy.environmentVariables]]
name = "N8N_DIAGNOSTICS_ENABLED"
value = "false"

[[deploy.environmentVariables]]
name = "N8N_VERSION_NOTIFICATIONS_ENABLED"
value = "false"

# Workflow execution settings
[[deploy.environmentVariables]]
name = "EXECUTIONS_PROCESS"
value = "main"

[[deploy.environmentVariables]]
name = "EXECUTIONS_TIMEOUT"
value = "300"

[[deploy.environmentVariables]]
name = "EXECUTIONS_TIMEOUT_MAX"
value = "600"
